### PR TITLE
Update Backbone, Underscore, and example

### PR DESCRIPTION
**Pull request by merrywhether**
Updated Backbone to 1.2.1, pulled out Underscore to allow npm to do dependency de-duping, added README to example to show how to build using Browserify

### CODE REVIEW

**Comment by dazld** [comment]
thanks for the PR - looks fine, but please remove the compiled app.js - no need to include compiled files here. I'll merge and bump the version on NPM when done :)

**Comment by merrywhether** [comment]
Ah, good catch. Totally forgot about that. Will fix shortly.

**Comment by merrywhether** [comment]
Sorry for the delay, pushed update.

**Comment by dazld** [comment]
looks good.

**Comment by dazld** [comment]
Published as `1.0.0`.

**Pull request merged**
